test/e2e/run: Wait for restarted instances to actually have an address
This is important later for the connectivity tests.

Signed-off-by: Julian Pelizäus <julian.pelizaeus@canonical.com>

diff --git a/test/e2e/run b/test/e2e/run
--- a/test/e2e/run
+++ b/test/e2e/run
@@ -289,14 +289,23 @@ evacuation() {
         fi
 
         lxc cluster restore --project e2e-testing --force "${REMOTE}:${member}"
-    done
 
-    echo -n "Allow time for stopped instances to start back again "
-    for _ in $(seq 20); do
-        echo -n "."
-        sleep 1
+        echo -n "Allow time for stopped instances on ${member} to start back again and have an IPv4 address"
+        for instance in $(instanceListByMember "${member}"); do
+            attempts=0
+            while [ -z "$(getIPv4 "${instance}")" ]; do
+                echo -n "."
+                sleep 1
+                attempts=$((attempts + 1))
+                if [ "${attempts}" -ge 30 ]; then
+                    echo " FAILED"
+                    exit 1
+                fi
+            done
+        done
+
+        echo " DONE"
     done
-    echo " DONE"
 }
 
 
